spring:
    datasource:
        url: jdbc:h2:file:~/data/connection.h2
        driverClassName: org.h2.Driver
        username: user
        password: password
        
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
